blog/urls.py
from django.urls import path
import django.views

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name = 'blog_index'),
    
    path('blog/<int:item_id>', views.blog_show, name = 'blog_show'),

    path('new_comment/<int:blog_id>', views.new_comment, name = 'new_comment'),

    path('delete_comment/<int:blog_id>/<int:comment_id>', views.delete_comment, name = 'delete_comment'),

    path('search_blog/', views.search_blog, name = 'search_blog'),

    path('tag_blogs/<str:tag_name>', views.tag_blogs, name = 'tag_blogs'),

    path('recommend_blogs/', views.recommend_blogs, name = 'recommend_blogs'),
]

home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.home, name = 'home'),
    path('gallery/', views.gallery, name = 'gallery'),
    path('lab/', views.lab, name = 'lab'),
    path('about/', views.about, name = 'about'),
    path('test_page/', views.test_page, name = 'test_page'),
    path('developing/', views.developing, name = 'developing'),
]

lab/urls.py
from django.urls import path
import django.views

from lab import views

app_name = 'lab'

urlpatterns = [
    # path('lab_index/', views.lab_index, name = 'lab_index'),
    path('text_embed/', views.text_embed, name = 'text_embed'),

    path('hash_verify/', views.hash_verify, name = 'hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('character_image/', views.character_image, name = 'character_image'),
]

schnee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('lab/', include('lab.urls', namespace = 'lab')),
    path('users/', include('users.urls', namespace = 'users')),
    path('lenotes/', include('lenotes.urls', namespace = 'lenotes')),
    path('sonata/', include('sonata.urls', namespace = 'sonata')),
    path('markdownx/', include('markdownx.urls')),
    path('simditor/', include('simditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.register, name = 'register'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    # 消息处理相关
    path('send_message/', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('receiver_del_message/<int:message_id>', views.receiver_del_message, name = 'receiver_del_message'),

    path('sender_del_message/<int:message_id>', views.sender_del_message, name = 'sender_del_message'),

    # 好友，群组处理相关
    path('add_as_friend/<int:user_id>', views.add_as_friend, name = 'add_as_friend'),

    path('deal_invi/<int:message_id>/<int:accept>', views.deal_invi, name = 'deal_invi'),

    path('delete_friend/<str:username>', views.delete_friend, name = 'delete_friend'),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),
]

lab/models.py
from django.db import models

# Create your models here.

home/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, StreamingHttpResponse, HttpResponse
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from helper.update_data import update_userInfo_unread_count

    
# Create your views here.
def index(requset):
    return render(requset, 'home/index.html')

def home(request):
    try:
        update_userInfo_unread_count(request.user)
    finally:
        return render(request, 'home/home.html')

def gallery(request):
    return render(request, 'home/gallery.html')

def lab(request):
    return render(request, 'home/lab.html')

def about(request):
    return render(request, 'home/about.html')

def test_page(request):
    return render(request, 'home/test_page.html')

def developing(request):
    return render(request, 'home/developing.html')

lab/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import Http404, HttpResponse
from django import forms

from PIL import Image
import numpy as np
import functools, zipfile, os, hashlib, random

# Create your views here.
def download_file(filename, aimname):
    file = open(filename, 'rb')  
    response = HttpResponse(file)  
    response['Content-Type'] = 'application/octet-stream'  
    response['Content-Disposition'] = 'attachment; filename = %s' % aimname  
    return response 

def text_embed(request):
    if request.method == 'POST':
        if request.POST['select_fun'] == "Extract info":
            return extract_info(request)
        else:
            return embedding_info(request)

    return render(request, 'lab/text_embed.html')

def embedding_info(request):
    if request.method == 'POST':
        text = request.POST['text']
        text = '#$#' + text
        text += '#%#' #作为结束标记
        
        img = request.FILES.get('beforeimg', None)

        accept_format = ['png', 'jpg', 'peg', 'bmp'] #peg -> jpeg
        if img.name[-3:] not in accept_format:
            raise Http404
        
        im = np.array(Image.open(img))        
        rows, columns, colors = im.shape
        embed = []
        for c in text:
            bin_sign = (bin(ord(c))[2:]).zfill(16)
            for i in range(16):
                embed.append(int(bin_sign[i]))
        
        count = 0
        for row in range(rows):
            for col in range(columns):
                for color in range(colors):
                    if count < len(embed):
                        im[row][col][color] = im[row][col][color] // 2 * 2 + embed[count]
                        count += 1

        # 这里将图片路径换成绝对路径，否则报错
        Image.fromarray(im).save('media/lab/Text_embed.png')

        return download_file('media/lab/Text_embed.png', 'Text_embed.png')

    content = {'text':'', 'selected':"Embedding info"}
    return render(request, 'lab/text_embed.html', content)
    

def extract_info(request):
    if request.method == 'POST':
        img = request.FILES.get('afterimg', None)

        # if not img.name.endswith('.png'):
        #     raise Http404
        
        accept_format = ['png', 'jpg', 'peg', 'bmp'] #peg -> jpeg
        if img.name[-3:] not in accept_format:
            raise Http404

        im = np.array(Image.open(img))
        rows, columns, colors = im.shape
        text = ""
        extract = np.array([], dtype = int)

        count = 0
        for row in range(rows):
            for col in range(columns):
                for color in range(colors):
                    extract = np.append(extract, im[row][col][color] % 2)
                    count += 1
                    if count % 16 == 0:
                        bcode = functools.reduce(lambda x, y: str(x) + str(y), extract)
                        cur_char = chr(int(bcode, 2))
                        text += cur_char
                        if len(text) == 3 and text != '#$#':
                            content = { 'text':'非标准格式文件，无法解密', 'selected':'Extract info'}
                            return render(request, 'lab/text_embed.html', content)
                        if cur_char == '#' and text[-3:] == '#%#':
                            content = { 'text':text[3:-3] }
                            return render(request, 'lab/text_embed.html', content)
                        extract = np.array([], dtype=int)

    return render(request, 'lab/text_embed.html')

def hash_verify(request):
    if request.method == 'POST':
        file = request.FILES.get('file', None)

        with open('media/lab/'+file.name, 'wb+') as f:
            for chunk in file.chunks():
                f.write(chunk)

        content = {}
        algorithm_names = ['md5', 'sha1', 'sha256', 'sha512']

        for name in algorithm_names:
            algorithm = hashlib.new(name)

            # read 1M one time
            read_size = 1024*1024
            with open('media/lab/'+file.name, 'rb') as f:
                while True:
                    b = f.read(read_size)
                    if b:
                        algorithm.update(b)
                    else:
                        break

            content[name] = algorithm.hexdigest()

        os.remove('media/lab/'+file.name)
        return render(request, 'lab/hash_verify.html', content)

    return render(request, 'lab/hash_verify.html')

def download_hash_verify(request):
    return download_file('media/lab/hash_verify.zip', 'hash_verify.zip')

# 将256灰度映射到70个字符上
ascii_char = list(r"$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\|()1{}[]?-_+~<>i!lI;:,\"^`'. ")

def get_char(r, g, b, alpha = 256):
    if alpha == 0:
        return ' '
    length = len(ascii_char)
    gray = int(0.2126 * r + 0.7152 * g + 0.0722 * b)

    unit = (256.0 + 1) / length
    return ascii_char[int(gray/unit)]

# 检查长宽是否在可接受范围内以及输入时候正确
def check_wh(src, default):
    try :
        src = int(src)
    except:
        src = default
    else:
        src = default if src not in list(range(10, 150)) else src
    return src

def character_image(request):
    if request.method == 'POST':
        img = request.FILES.get('img', None)
        imgformat = request.POST['format']
        
        accept_format = ['png', 'jpg', 'peg', 'bmp'] #peg -> jpeg
        if img.name[-3:] not in accept_format:
            raise Http404

        im = Image.open(img)
        w, h = im.size

        height = request.POST['height']
        height = check_wh(height, 80)
        try:
            autowidth = request.POST['autowidth']
        except Exception as e:
            width = request.POST['width']
            width = check_wh(width, 120)
        else:
            width = w * height // h
        
        im = im.resize((width, height), Image.NEAREST)

        txt = ""

        for i in range(height):
            for j in range(width):
                txt += get_char(*im.getpixel((j, i)))
            txt += '\n'

        with open('media/lab/character_image.txt', 'w') as f_obj:
            f_obj.write(txt)
             
        return download_file('media/lab/character_image.txt', 'character_image.txt')

    return render(request, 'lab/character_image.html')

home/templates/home/base.html
<!DOCTYPE html> {% load bootstrap4 %} {% load staticfiles %} {% load base %}
<html lang="en">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../../../static/img/four.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Schnee</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
            CSS
            ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <!-- start banner Area -->
    <section class="banner-area" id="home">
        <!-- Start Header Area -->
        <div id="undefined-sticky-wrapper" class="sticky-wrapper is-sticky" style="height: 56px;">
            <header class="default-header" style="width: 1090px; position: fixed; top: 0px;">
                <nav class="navbar navbar-expand-lg  navbar-light">
                    <div class="container">
                        <a class="navbar-brand" href="{% url 'home:index' %}">
                            <img src="/static/img/logo_schnee.png" alt="">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="text-white lnr lnr-menu"></span>
                          </button>

                        <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li><a href="{% url 'home:home' %}">Home</a></li>
                                <li><a href="{% url 'blog:blog_index' %}">Blog</a></li>
                                <!-- <li><a href="{% url 'home:gallery' %}">Gallery</a></li> -->
                                <li><a href="{% url 'home:lab' %}">Lab</a></li>
                                <li><a href="{% url 'lenotes:index' %}">Lenotes</a></li>
                                <li><a href="{% url 'home:about' %}">About</a></li>
                                <!-- <li><a href="{% url 'home:test_page' %}">TestPage</a></li> -->
                                <li><a href="#" style="padding: 0px">|</a></li>
                                <!-- Dropdown -->
                                {% if user.is_authenticated %}
                                <li>
                                    <a href="{% url 'users:notice' %}">Notice
                                        {% ifnotequal user|getUnreadCount 0 %}
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        <!-- <span class="glyphicon glyphicon-info-sign">{{ user|getUnreadCount }}</span> -->
                                        {% endifnotequal %}
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="{% url 'users:settings' %}" id="navbardrop" data-toggle="dropdown"> {{user.username}}
                                        <span class="caret"></span></a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url 'users:send_message' %}">Send Message</a>
                                        <a class="dropdown-item" href="{% url 'users:settings' %}">Settings</a>
                                        <a role="presentation" class="divider"></a>
                                        <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
                                    </div>
                                </li>
                                {% else %}
                                <li><a href="{% url 'users:login' %}">Log In</a></li>
                                <li><a href="{% url 'users:register' %}">Register</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        </div>

        <!-- End Header Area -->
    </section>



    <div class="container">
        <div>
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>

    </div>



    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <!-- <script src="{% static 'js/jquery.sticky.js' %}"></script> -->
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

home/templates/home/developing.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} About {% endblock %} {% block content %} {% load static %}

<body>
    <!-- Start about Area -->
    <section class="section-gap info-area" id="about">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-40 col-lg-8">
                    <div class="title text-center">
                        <br/>
                        <h1 class="mb-10">Developing, keep on update n_n</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>
{% endblock content %}

home/templates/home/home.html
<!DOCTYPE html> {% extends "home/base.html" %} {% block title %} Home {% endblock %} {% block content %} {% load static %} {% load staticfiles %}
<html lang="zxx" class="no-js">

<body>
    <!-- Start project Area -->
    <section class="project-area section-gap" id="project" style="padding-top: 50px">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-30 col-lg-8">
                    <div class="title text-center">
                        <h1 class="mb-10">Introduction and Arbitrary gate</h1>
                        <p>Why we have this page? Just for fun n _ n</p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center d-flex">
                <div class="active-works-carousel mt-40 col-lg-8">
                    <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P1.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'home:home' %}" style="color:#000000">
                                <h6>Home</h6>
                                <p>The current page, including the introduction of other pages.</p>
                            </a>
                        </div>
                    </div>
                    <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P2.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'blog:blog_index' %}" style="color:#000000">
                                <h6>Blog</h6>
                                <p>The main function, to share what I have learned.</p>
                            </a>
                        </div>
                    </div>
                    <!-- <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P3.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'home:gallery' %}" style="color:#000000">
                                <h6>Gallery</h6>
                                <p>Like travel, like photography, like sharing.</p>
                            </a>
                        </div>
                    </div> -->
                    <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P4.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'home:lab' %}" style="color:#000000">
                                <h6>Lab</h6>
                                <p>Something new and fun. Just for test~</p>
                            </a>
                        </div>
                    </div>
                    <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P3.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'lenotes:index' %}" style="color:#000000">
                                <h6>Lenotes</h6>
                                <p>Public notebook, markdown supported.</p>
                            </a>
                        </div>
                    </div>
                    <div class="item">
                        <img class="img-fluid" src="{% static 'img/home/P5.jpg' %}" alt="">
                        <div class="caption text-center mt-20">
                            <a href="{% url 'home:about' %}" style="color:#000000">
                                <h6>About</h6>
                                <p>Personal information. You can know more about me.</p>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End project Area -->
    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

<!-- {% endblock content %} -->

home/templates/home/index.html
<!DOCTYPE html> {% load base %} {% load staticfiles %} {% load bootstrap4 %}
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../../../static/img/four.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Schnee</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body style="overflow-y: hidden">
    <!-- start banner Area -->
    <section class="banner-area" id="home">
        <!-- Start Header Area -->
        <header class="default-header">
            <nav class="navbar navbar-expand-lg  navbar-light">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'home:index' %}">
                        <img src="{% static 'img/logo_schnee.png' %}" alt="">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="text-white lnr lnr-menu"></span>
                          </button>

                    <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li><a href="{% url 'home:home' %}">Home</a></li>
                            <li><a href="{% url 'blog:blog_index' %}">Blog</a></li>
                            <!-- <li><a href="{% url 'home:gallery' %}">Gallery</a></li> -->
                            <li><a href="{% url 'home:lab' %}">Lab</a></li>
                            <li><a href="{% url 'lenotes:index' %}">Lenotes</a></li>
                            <li><a href="{% url 'home:about' %}">About</a></li>
                            <li><a href="#" style="padding: 0px">|</a></li>
                            {% if user.is_authenticated %}

                            <li>
                                <a href="{% url 'users:notice' %}">Notice
                                        {% ifnotequal user|getUnreadCount 0 %}
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        <!-- <span class="glyphicon glyphicon-info-sign">{{ user|getUnreadCount }}</span> -->
                                        {% endifnotequal %}
                                    </a>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="{% url 'users:settings' %}" id="navbardrop" data-toggle="dropdown"> {{user.username}}
                                        <span class="caret"></span></a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="{% url 'users:send_message' %}">Send Message</a>
                                    <a class="dropdown-item" href="{% url 'users:settings' %}">Settings</a>
                                    <a role="presentation" class="divider"></a>
                                    <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
                                </div>
                            </li>
                            {% else %}
                            <li><a href="{% url 'users:login' %}">Log In</a></li>
                            <li><a href="{% url 'users:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- End Header Area -->
    </section>

    <section class="default-banner active-blog-slider">
        <div class="item-slider relative" style="background: url(../../../static/img/slider1.jpg);background-size: cover;">
            <div class="overlay" style="background: rgba(0,0,0,.3)"></div>
            <div class="container">
                <div class="row fullscreen justify-content-center align-items-center">
                    <div class="col-md-10 col-12">
                        <div class="banner-content text-center">
                            <h4 class="text-white mb-20 text-uppercase">Discover the Colorful World</h4>
                            <h1 class="text-uppercase text-white">New Adventure</h1>
                            <!-- <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp <br> or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p> -->
                            <a href="{% url 'home:home' %}" class="text-uppercase header-btn">Discover Now</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="item-slider relative" style="background: url(../../../static/img/slider2.jpg);background-size: cover;">
            <div class="overlay" style="background: rgba(0,0,0,.3)"></div>
            <div class="container">
                <div class="row fullscreen justify-content-center align-items-center">
                    <div class="col-md-10 col-12">
                        <div class="banner-content text-center">
                            <h4 class="text-white mb-20 text-uppercase">Discover the Colorful World</h4>
                            <h1 class="text-uppercase text-white">New Trip</h1>
                            <!-- <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp <br> or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p> -->
                            <a href="{% url 'home:home' %}" class="text-uppercase header-btn">Discover Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="item-slider relative" style="background: url(../../../static/img/slider3.jpg);background-size: cover;">
            <div class="overlay" style="background: rgba(0,0,0,.3)"></div>
            <div class="container">
                <div class="row fullscreen justify-content-center align-items-center">
                    <div class="col-md-10 col-12">
                        <div class="banner-content text-center">
                            <h4 class="text-white mb-20 text-uppercase">Discover the Colorful World</h4>
                            <h1 class="text-uppercase text-white">New Experience</h1>
                            <!-- <p class="text-white">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod temp <br> or incididunt ut labore et dolore magna aliqua. Ut enim ad minim.</p> -->
                            <a href="{% url 'home:home' %}" class="text-uppercase header-btn">Discover Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/jquery.sticky.js' %}"></script>
    <script src="{% static 'js/slick.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/waypoints.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>

</html>

home/templates/home/userIsNotExist.html
{% extends "lenotes/base.html" %} {% load widget_tweaks %} {% block title %}Error in invite{% endblock title %} {% block content %}

<h1>The user is not Exist</h1>
<a href="javascript:history.go(-1)" class="btn btn-primary">comfirm</a> {% endblock content %}