home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.home, name = 'home'),
    path('gallery/', views.gallery, name = 'gallery'),
    path('lab/', views.lab, name = 'lab'),
    path('about/', views.about, name = 'about'),
    path('test_page/', views.test_page, name = 'test_page'),
    path('developing/', views.developing, name = 'developing'),
]

lab/urls.py
from django.urls import path
import django.views

from lab import views

app_name = 'lab'

urlpatterns = [
    # path('lab_index/', views.lab_index, name = 'lab_index'),
    path('text_embed/', views.text_embed, name = 'text_embed'),

    path('hash_verify/', views.hash_verify, name = 'hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('character_image/', views.character_image, name = 'character_image'),
]

lenotes/urls.py
from django.urls import path
import django.views

from lenotes import views

app_name = 'lenotes'

urlpatterns = [
    path('index/', views.index, name = 'index'),

    path('home/', views.home, name = 'home'),

    path('group/<int:group_id>', views.group, name = 'group'),

    path('diary_month/<int:group_id>/<int:year>/<int:month>', views.diary_month, name = 'diary_month'),

    path('manage/<int:group_id>', views.manage, name = 'manage'),
    
    path('del_member/<int:group_id><int:info_id>', views.del_member, name = 'del_member'),

    path('send_invite/<int:group_id>', views.send_invite, name = 'send_invite'),

    path('new_group/', views.new_group, name = 'new_group'),

    path('del_group/<int:group_id>', views.del_group, name = 'del_group'),

    path('new_diary/<int:group_id>', views.new_diary, name = 'new_diary'),

    path('edit_diary_md/<int:diary_id>', views.edit_diary_md, name = 'edit_diary_md'),

    path('diary_log/<int:diary_id>', views.diary_log, name = 'diary_log'),

    path('lenotes_intro/', views.lenotes_intro, name = 'lenotes_intro'),
]

schnee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('lab/', include('lab.urls', namespace = 'lab')),
    path('users/', include('users.urls', namespace = 'users')),
    path('lenotes/', include('lenotes.urls', namespace = 'lenotes')),
    path('sonata/', include('sonata.urls', namespace = 'sonata')),
    path('markdownx/', include('markdownx.urls')),
    path('simditor/', include('simditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

sonata/urls.py
from django.urls import path
import django.views

from sonata import views

app_name = 'sonata'

urlpatterns = [
    path('', views.article_index, name = 'article_index'),
    
    path('sonata/<int:item_id>', views.article_show, name = 'article_show'),

    path('new_comment/<int:article_id>', views.new_comment, name = 'new_comment'),

    path('delete_comment/<int:article_id>/<int:comment_id>', views.delete_comment, name = 'delete_comment'),

    path('search_article/', views.search_article, name = 'search_article'),

    path('tag_articles/<str:tag_name>', views.tag_articles, name = 'tag_articles'),

    path('recommend_articles/', views.recommend_articles, name = 'recommend_articles'),
]

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.register, name = 'register'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    # 消息处理相关
    path('send_message/', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('receiver_del_message/<int:message_id>', views.receiver_del_message, name = 'receiver_del_message'),

    path('sender_del_message/<int:message_id>', views.sender_del_message, name = 'sender_del_message'),

    # 好友，群组处理相关
    path('add_as_friend/<int:user_id>', views.add_as_friend, name = 'add_as_friend'),

    path('deal_invi/<int:message_id>/<int:accept>', views.deal_invi, name = 'deal_invi'),

    path('delete_friend/<str:username>', views.delete_friend, name = 'delete_friend'),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),
]

lenotes/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from datetime import datetime
# Create your models here.


class Group(models.Model):
    name = models.CharField(max_length = 40, default="example group")
    intro = models.CharField(max_length = 200, default="no introduce")
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE, related_name='group_owner')
    members = models.ManyToManyField(User)
    profile = ProcessedImageField(upload_to='group/img', default='group/img/default.jpg', 
        processors=[ResizeToFill(750, 465)],  format='JPEG', options={'quality': 60})
    
    def __str__(self):
        return self.name

class Diary(models.Model):
    content = MarkdownxField()
    date_added = models.DateTimeField(auto_now_add = True)
    group = models.ForeignKey(Group,on_delete = models.CASCADE)
    diary_log = models.TextField(default=str(date_added) + "  Create diary")
    
    def __str__(self):
        return self.content

lenotes/forms.py
from django import forms
from lenotes.models import Group, Diary
from markdownx.fields import MarkdownxFormField

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = [
            'name',
            'intro',
        ]
        labels = {
            'name': 'Group Name',
            'intro': 'Group Introduce',
        }

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = [
            'content',
        ]
        labels = {
            'content' : 'Content ( Markdown supportted )',
        }
    def __init__(self, *args, **kwargs):
        super(DiaryForm, self).__init__(*args, **kwargs)
        self.fields['content'] = MarkdownxFormField()
        self.fields['content'].label = 'Content ( Markdown supportted )'

home/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, StreamingHttpResponse, HttpResponse
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from helper.update_data import update_userInfo_unread_count

    
# Create your views here.
def index(requset):
    return render(requset, 'home/index.html')

def home(request):
    try:
        update_userInfo_unread_count(request.user)
    finally:
        return render(request, 'home/home.html')

def gallery(request):
    return render(request, 'home/gallery.html')

def lab(request):
    return render(request, 'home/lab.html')

def about(request):
    return render(request, 'home/about.html')

def test_page(request):
    return render(request, 'home/test_page.html')

def developing(request):
    return render(request, 'home/developing.html')

lenotes/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, Http404, StreamingHttpResponse, HttpResponse
from django.shortcuts import render

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from lenotes.models import Group, Diary
from users.models import UserInfo, Message
from lenotes.forms import GroupForm, DiaryForm
from helper.update_data import update_userInfo_unread_count

from datetime import datetime
from PIL import Image

import json

def check_user(request, group, flag): 
    """
        flag 0 检查是不是群主
        flag 1 检查是不是群成员
    """
    if flag == 0 and request.user != group.owner:
        raise Http404
    elif flag == 1 and request.user not in group.members.all():
        raise Http404

def index(request):
    if request.user.is_authenticated:
        update_userInfo_unread_count(request.user)
    return render(request, 'lenotes/index.html')

@login_required
def home(request):
    """显示个人信息的主界面"""
    try:
        userinfo = UserInfo.objects.get(user=request.user) 
    except ObjectDoesNotExist:
        userinfo = UserInfo.objects.create(user=request.user)
    if userinfo.nickname.strip() == "":
        userinfo.nickname = "Undefined"
    if userinfo.gender.strip() == "M":
        userinfo.gender = "Male"
    else:
        userinfo.gender = "Female"
    if userinfo.email.strip() == "":
        userinfo.email = "Undefined@example.com"
    if userinfo.intro.strip() == "":
        userinfo.intro = "No introduce"
    update_userInfo_unread_count(request.user)
    groups = Group.objects.filter(members__id = request.user.id).order_by('date_added')
    context = {
        'userinfo': userinfo,
        'groups' : groups,
    }
    return render(request, 'lenotes/home.html', context)

@login_required
def group(request, group_id):
    """群组主页"""
    year, month = datetime.now().year, datetime.now().month
    return HttpResponseRedirect(reverse('lenotes:diary_month', args=[group_id, year, month]))

@login_required   
def diary_month(request, group_id, year, month):
    group = Group.objects.get(id=group_id)
    check_user(request, group, 1)
    tdiary = group.diary_set.order_by('-date_added')
    createJudge = False
    if tdiary.count() == 0:
        createJudge = True
    elif tdiary[0].date_added.year != datetime.now().year or tdiary[0].date_added.month != datetime.now().month\
        or tdiary[0].date_added.day != datetime.now().day:
        createJudge = True  

    diarys = group.diary_set.filter(date_added__year=year, date_added__month = month).order_by('date_added')
    lastMonth, lastYear, nextMonth, nextYear = 0, 0, 0, 0
    
    lastMonthJudge = False if tdiary.count() == 0 or month == tdiary[len(tdiary)-1].date_added.month else True
    nextMonthJudge = False if month == datetime.now().month else True
    
    if month==1:
        lastMonth = 12
        lastYear = year-1
    else:
        lastMonth = month-1
        lastYear = year
    
    if month==12:
        nextMonth = 1
        nextYear = year+1
    else:
        nextMonth = month+1
        nextYear = year
    
    context = {
        'group': group, 
        'diarys': diarys, 
        'lastMonth': lastMonth,
        'lastYear': lastYear,
        'nextMonth': nextMonth,
        'nextYear': nextYear,
        'createJudge': createJudge,
        'lastMonthJudge': lastMonthJudge,
        'nextMonthJudge': nextMonthJudge,
    }
   
    return render(request, 'lenotes/group_diary_md.html', context)

@login_required
def manage(request, group_id):
    """修改群组资料，邀请功能，管理用户"""
    if request.method != 'POST':
        try:
            group = Group.objects.get(id=group_id)
        except ObjectDoesNotExist:
            group = Group.objects.create(id=group_id)
        group_form = GroupForm(instance = group)
    else:
        group_form = GroupForm(request.POST, request.FILES)
        if group_form.is_valid():
            try:
                group = Group.objects.get(id=group_id)
            except ObjectDoesNotExist:
                group = Group.objects.create(id=group_id)
        group.name = group_form.cleaned_data["name"]
        group.intro = group_form.cleaned_data["intro"]
        myprofile = request.FILES.get('profile',None)
        if myprofile:
            if group.profile.name != 'group/img/default.jpg':
                group.profile.delete()
            group.profile = myprofile
        group.save()
        return HttpResponseRedirect(reverse('lenotes:group', args=[group.id]))
    
    check_user(request, group, 1)
    members = group.members.all()
    memberInfos = []
    for member in members:
        info = UserInfo.objects.get(user=member)
        memberInfos.append(info)
    context = {
        'group': group,
        'memberInfos': memberInfos,
        'group_form': group_form,
    }
    return render(request, 'lenotes/manage.html' , context)


@login_required
def del_member(request, group_id, info_id):
    group = Group.objects.get(id=group_id)
    check_user(request, group, 0)
    info = UserInfo.objects.get(id=info_id)
    group.members.remove(info.user)
    msg = "You have been removed from group: " + group.name
    Message.objects.create(sender=group.owner, text=msg, receiver=info.user)
    return HttpResponseRedirect(reverse('lenotes:manage', args=[group_id]))


@login_required
def send_invite(request, group_id):
    if request.method == 'POST':
        try:
            receiver = User.objects.get(username=request.POST['invite_id'])
        except ObjectDoesNotExist:
            context = {'group_id': group_id}
            return render(request, 'home/userIsNotExist.html' , context)
        group = Group.objects.get(id = group_id)
        check_user(request, group, 0)
        msg = request.user.username + " invite you to join Group: " + group.name + "."
        Message.objects.create(sender=request.user, receiver=receiver, 
            text=msg, id_content=group.id, msg_type="Group_Invitation")
        
        return HttpResponseRedirect(reverse('lenotes:manage', args=[group_id]))
        
    group = Group.objects.get(id = group_id)
    check_user(request, group, 0)
    context = { 'group_id': group_id }
    return render(request, 'lenotes/send_invite.html', context)

@login_required
def new_group(request):
    if request.method != 'POST':
        form = GroupForm()
    else:
        form = GroupForm(request.POST, request.FILES)
        if form.is_valid():
            new_group = form.save(commit=False)
            new_group.owner = request.user
            new_group.save()
            new_group.members.add(request.user)
            return HttpResponseRedirect(reverse('lenotes:home'))
    
    context = { 'form': form }
    return render(request, 'lenotes/new_group.html', context)

@login_required
def del_group(request, group_id):
    """删除当前群组"""
    del_group = Group.objects.get(id=group_id)
    check_user(request, del_group, 0)
    members = del_group.members.all()
    senderName = del_group.owner.username + "(Group Owner)"
    for member in members:
        msg = "The group: " + del_group.name + " have been deleted."
        Message.objects.create(sender=senderName, text=msg, receiver=member)
    del_group.delete()
    return HttpResponseRedirect(reverse('lenotes:home'))

@login_required
def new_diary(request, group_id):
    group = Group.objects.get(id = group_id)
    check_user(request, group, 1)
    if request.method != 'POST':
        form = DiaryForm()
    else:
        form = DiaryForm(data = request.POST)
        if form.is_valid():
            new_diary = form.save(commit=False)
            new_diary.group = group
            new_diary.save()
            return HttpResponseRedirect(reverse('lenotes:group', args=[group_id]))
    context = {'group': group, 'form': form}
    return render(request, 'lenotes/new_diary.html', context)

@login_required
def edit_diary_md(request, diary_id):
    """编辑既有条目"""
    diary = Diary.objects.get(id=diary_id)
    group = diary.group
    check_user(request, group, 1)
    if request.method != 'POST':
        form = DiaryForm(instance=diary)
    else:
        form = DiaryForm(instance=diary, data=request.POST)
        if form.is_valid():
            # diary_log 需要重新处理
            diary.diary_log = (str(datetime.now()) + "  Editor: " + str(request.user) + "\r\n") + diary.diary_log
            form.save()
            return HttpResponseRedirect(reverse('lenotes:diary_month', 
                args=[group.id, diary.date_added.year, diary.date_added.month]))
    context = {
        'diary': diary, 
        'group': group, 
        'form': form
    }
    return render(request, 'lenotes/edit_diary_md.html', context)

@login_required
def diary_log(request, diary_id):
    diary_log = Diary.objects.get(id=diary_id).diary_log
    context = { 'diary_log': diary_log }
    return render(request, 'lenotes/diary_log.html', context)


def lenotes_intro(request):
    return render(request, 'lenotes/lenotes_intro.html')

lenotes/templates/lenotes/base.html
<!DOCTYPE html> {% load bootstrap4 %} {% load staticfiles %} {% load base %}
<html lang="en">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="../../../static/img/four.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Lenotes</title>

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
    <!--
            CSS
            ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    <!-- start banner Area -->
    <section class="banner-area" id="home">
        <!-- Start Header Area -->
        <div id="undefined-sticky-wrapper" class="sticky-wrapper is-sticky" style="height: 56px;">
            <header class="default-header" style="width: 1090px; position: fixed; top: 0px;">
                <nav class="navbar navbar-expand-lg  navbar-light">
                    <div class="container">
                        <a class="navbar-brand" href="{% url 'home:index' %}">
                            <img src="/static/img/logo_schnee.png" alt="">
                        </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="text-white lnr lnr-menu"></span>
                          </button>

                        <div class="collapse navbar-collapse justify-content-end align-items-center" id="navbarSupportedContent" style="height: 22px">
                            <ul class="navbar-nav">
                                <li><a href="{% url 'lenotes:index' %}">Lenotes</a></li>
                                <li><a href="{% url 'lenotes:home' %}">Home</a></li>
                                <li><a href="{% url 'sonata:article_index' %}">Sonata</a></li>
                                <li><a href="{% url 'home:about' %}">About</a></li>
                                <!-- <li><a href="{% url 'home:test_page' %}">TestPage</a></li> -->
                                <li><a href="#" style="padding: 0px">|</a></li>
                                <!-- Dropdown -->
                                {% if user.is_authenticated %}
                                <li>
                                    <a href="{% url 'users:notice' %}">Notice
                                        {% ifnotequal user|getUnreadCount 0 %}
                                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                                        <!-- <span class="glyphicon glyphicon-info-sign">{{ user|getUnreadCount }}</span> -->
                                        {% endifnotequal %}
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a class="dropdown-toggle" href="{% url 'users:settings' %}" id="navbardrop" data-toggle="dropdown"> {{user.username}}
                                        <span class="caret"></span></a>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="{% url 'users:send_message' %}">Send Message</a>
                                        <a class="dropdown-item" href="{% url 'users:settings' %}">Settings</a>
                                        <a role="presentation" class="divider"></a>
                                        <a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a>
                                    </div>
                                </li>

                                {% else %}
                                <li><a href="{% url 'users:login' %}">Log In</a></li>
                                <li><a href="{% url 'users:register' %}">Register</a></li>
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        </div>

        <!-- End Header Area -->
    </section>



    <div class="container">
        <div>
            {% block header %}{% endblock %}
        </div>
        <div>
            {% block content %}{% endblock %}
        </div>
    </div>


    <div id="Display" style="position:fixed; right:60px; bottom:20px; z-index:-1">
        <img src="{% static 'img/fox_180.gif' %}" />
    </div>

    <script>
        window.onresize = function() {
            chg();
        }

        function chg() {
            if (window.innerWidth <= 960) {
                document.getElementById("Display").style.display = "none";
            } else {
                document.getElementById("Display").style.display = "";
            }
        }
    </script>

    <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
</body>

</html>

lenotes/templates/lenotes/edit_diary_md.html
<!DOCTYPE html> {% extends "lenotes/base.html" %} {% load bootstrap4 %} {% block content %}

<section class="project-area section-gap" id="project" style="padding-top: 50px">
    <div class="banner-body">
        <div class="container">
            <h3><a href="{% url 'lenotes:group' group.id %}">{{ group }}</a></h3>
            <br/>
            <h4>Edit Diary:</h4>

            <form action="{% url 'lenotes:edit_diary_md' diary.id %}" method='post' class="form">
                {% csrf_token %} {% bootstrap_form form %} {% buttons %}
                <button name="submit" class="btn btn-primary">Save changes</button> {% endbuttons %}
            </form>{{ form.media }} {% endblock content %}
        </div>
    </div>
</section>

lenotes/templates/lenotes/home.html
<!DOCTYPE html> {% extends "lenotes/base.html" %} {% block header %} {% load static %} {% load bootstrap4 %}
<html>

<head>
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/homestyle.css' %}">
</head>

<body>
    <section class="project-area section-gap" id="project" style="padding: 50px 0px 150px 0px">
        <div class="banner-body">
            <div class="container">
                <div style="margin:0 90px 0 290px; float: left;">
                    <img class="img-circle" style="width:150px; height:150px; overflow:hidden;" src="/media/{{userinfo.profile}}" alt="">
                </div>
                <div style="float: left">
                    <div class="nickname_info">{{ userinfo.nickname }}</div>
                    <div class="gender_info">{{ userinfo.gender }}</div>
                    <br/>
                    <div class='email_info'>{{ userinfo.email }}</div>
                    <br/>
                    <div class='user_info'>{{ userinfo.intro }}</div>
                </div>
                <div class="clear"></div>

                <div style='margin: 50px 0 0 0'>
                    <hr>
                    <div class="msg-text-bottom">
                        {% for group in groups %}
                        <div class="msg-text-bottom-left" style="width: 280px; height: 320px;  float: left;">
                            <figure class="effect-winston">
                                <a href="{% url 'lenotes:group' group.id %} "><img src="/media/{{group.profile}}" alt=" " class="img-responsive" />
                                </a>
                            </figure>
                            <h3><a href="{% url 'lenotes:group' group.id %} ">{{ group.name }}</a></h3>
                            <p class='my_content'>{{ group.intro }}</p>
                            <br/>
                        </div>
                        {% endfor %}
                        <div class="clearfix"> </div>
                    </div>
                    <br/>
                    <br/>
                    <h4><a href="{% url 'lenotes:new_group' %} " class="btn btn-default creat_group_button">Create new group</a></h4>
                    <br/>
                    <br/>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

{% endblock %}

lenotes/templates/lenotes/index.html
<!DOCTYPE html> {% extends "lenotes/base.html" %} {% load bootstrap4 %} {% load staticfiles %} {% load base %} {% block header %}
<html lang="en">

<head>
    <title>Lenotes</title>
    <meta charset="utf-8">

</head>

<body>
    <section class="project-area section-gap" id="project" style="padding-top: 50px">
        <div class="section_title">
            <h2>What is Lenotes?</h2>
        </div>
        <br/>
        <br/>
        <div class="services_list">
            <p>Lenotes 是 Schnee 的子模块，主要用于娱乐功能，主要功能有：</p>
            <h3>Home</h3>
            <br/>
            <p>用户个人主页，可查看所拥有的公共日记本，创建新的日记，邀请好友进入群组共同编辑</p>
            <p>点击查看 <a href="{% url 'lenotes:lenotes_intro' %}">Lenotes使用说明</a></p>
            <h3>Sonata</h3>
            <br/>
            <p>分享我的故事与读书心得，与志同道合的朋友交流</p>
        </div>
        <br/>
        <br/>
        <a href="{% url 'home:home' %}" class="btn btn-info">Return Schnee</a>
    </section>
</body>
<hr>

</html>



{% endblock %}

lenotes/templates/lenotes/manage.html
<!DOCTYPE html> {% extends "lenotes/base.html" %} {% load widget_tweaks %} {% load bootstrap4 %} {% block title %}Menage{% endblock title %} {% block content %}

<script type="text/javascript">
    function delGroupConfirm() {
        event.returnValue = confirm("Are you sure to delete this group?")
    }

    function quitGroupConfirm() {
        event.returnValue = confirm("Are you sure to quit this group?")
    }

    function delMemberConfirm() {
        event.returnValue = confirm("Are you sure to delete this member?")
    }
</script>

<section class="project-area section-gap" id="project" style="padding-top: 50px">
    <div class="banner-body">
        <div class="container">
            <form action="{% url 'lenotes:manage' group.id %}" enctype="multipart/form-data" method='post' novalidate class="myforms">
                {% csrf_token %}
                <h2>Manage</h2>
                <hr/> {% for field in group_form %}
                <div class="form-group">
                    <span>{{ field.label }}</span> {{ field | add_class:"form-control"}}
                    <p class="error-message text-danger">
                        {% for error in field.errors %} {{ error }} {% endfor %}
                    </p>
                </div>

                {% endfor %} {{ group_form.media }}

                <div class="form-group">
                    <span>Profile Photo(Only support english filename)</span>
                    <input type="file" name="profile" class="form-control" />
                </div>


                <br/> {% ifequal group.owner request.user %}
                <a href="{% url 'lenotes:del_group' group.id %}" class="btn btn-danger" onclick="delGroupConfirm()">Delete Group</a> {% else %}
                <a href="{% url 'users:quit_group' group.id %}" class="btn btn-danger" onclick="quitGroupConfirm()">Quit the group</a> {% endifequal %}
                <br/><br/>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>UserName</th>
                            <th>Gender</th>
                            <th>Email</th>
                            <th>introduce</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for info in memberInfos %}
                        <tr>
                            {% if group.owner == info.user %}
                            <td>{{ info.nickname }} (Group Owner)</td>
                            {% elif request.user == info.user %}
                            <td>{{ info.nickname }} (Yourself)</td>
                            {% else %}
                            <td>{{ info.nickname }}</td>
                            {% endif %}
                            <td>{{ info.gender }}</td>
                            <td>{{ info.email }}</td>
                            <td>{{ info.intro }}</td>
                            {% ifequal group.owner request.user %} {% ifnotequal group.owner info.user %}
                            <td>
                                <a href="{% url 'lenotes:del_member' group.id info.id %}" onclick="delMemberConfirm()" title="Delete">
                                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                                </a>
                            </td>
                            {% endifnotequal %} {% endifequal %}
                        </tr>
                        {% empty %}
                        <li>Only you and no other Member.</li>
                        {% endfor %}
                    </tbody>
                </table>

                {% ifequal group.owner request.user %}
                <a href="{% url 'lenotes:send_invite' group.id %}" class="btn btn-outline-success">Invite new member</a> {% endifequal %}


                <div style="text-align: center">
                    <button name="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" href="{% url 'lenotes:home' %}">Go Back</a>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}