blog/urls.py
from django.urls import path
import django.views

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_index, name = 'blog_index'),
    
    path('blog/<int:item_id>', views.blog_show, name = 'blog_show'),

    path('new_comment/<int:blog_id>', views.new_comment, name = 'new_comment'),

    path('delete_comment/<int:blog_id>/<int:comment_id>', views.delete_comment, name = 'delete_comment'),

    path('search_blog/', views.search_blog, name = 'search_blog'),

    path('tag_blogs/<str:tag_name>', views.tag_blogs, name = 'tag_blogs'),

    path('recommend_blogs/', views.recommend_blogs, name = 'recommend_blogs'),
]

lab/urls.py
from django.urls import path
import django.views

from lab import views

app_name = 'lab'

urlpatterns = [
    # path('lab_index/', views.lab_index, name = 'lab_index'),
    path('text_embed/', views.text_embed, name = 'text_embed'),

    path('hash_verify/', views.hash_verify, name = 'hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('character_image/', views.character_image, name = 'character_image'),
]

schnee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('lab/', include('lab.urls', namespace = 'lab')),
    path('users/', include('users.urls', namespace = 'users')),
    path('lenotes/', include('lenotes.urls', namespace = 'lenotes')),
    path('sonata/', include('sonata.urls', namespace = 'sonata')),
    path('markdownx/', include('markdownx.urls')),
    path('simditor/', include('simditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.register, name = 'register'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    # 消息处理相关
    path('send_message/', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('receiver_del_message/<int:message_id>', views.receiver_del_message, name = 'receiver_del_message'),

    path('sender_del_message/<int:message_id>', views.sender_del_message, name = 'sender_del_message'),

    # 好友，群组处理相关
    path('add_as_friend/<int:user_id>', views.add_as_friend, name = 'add_as_friend'),

    path('deal_invi/<int:message_id>/<int:accept>', views.deal_invi, name = 'deal_invi'),

    path('delete_friend/<str:username>', views.delete_friend, name = 'delete_friend'),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation

from simditor.fields import RichTextField
from markdownx.models import MarkdownxField

from view_record.models import ViewNum

# Create your models here.
class Tag(models.Model):
    tag_name = models.CharField(max_length=20, default='')
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.tag_name


class Blog(models.Model):
    caption = models.CharField(max_length=50, default='')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    content = RichTextField()
    
    read_num = models.IntegerField(default=0)
    publish_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    recommend = models.BooleanField(default=False)

    view_num = GenericRelation(ViewNum)

    def __str__(self):
        return u'%s %s %s' % (self.caption, self.author, self.publish_time)

    class Meta:
        ordering = ['-publish_time']

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_time = models.DateTimeField(auto_now_add=True)
    content = models.TextField(max_length=400, default='')

    class Meta:
        ordering = ['-publish_time']

    def __str__(self):
        return u'%s %s %s' % (self.blog, self.author, self.content)

# class Reply(models.Model):
#     comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
#     author = models.ForeignKey(User, on_delete=models.CASCADE)
#     publish_time = models.DateTimeField(auto_now_add=True)
#     content = models.TextField(max_length=400, default='')

#     class Meta:
#         ordering = ['-publish_time']

#     def __str__(self):
#         return u'%s %s %s' % (self.comment, self.author, self.content)

blog/forms.py
from django import forms
#from markdown import MarkdownFormField
from blog.models import Tag, Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            'caption',
            'content',
        ]
        labels = {
            'caption': 'Caption',
            'content': ''
        }

blog/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponseRedirect, Http404

from view_record.decorator import record_view
from helper.paginator import getPages
from blog.models import Blog, Tag, Comment
from blog.forms import BlogForm
from users.models import Message

import random

# 博客相关视图函数

def random_recommend():
    blogs = Blog.objects.all()
    num = 7 if len(blogs) >= 7 else len(blogs) 
    random_blogs = random.sample(list(blogs), num)
    return sorted(random_blogs, key=lambda x: x.publish_time, reverse=True)

def author_recommend():
    blogs = Blog.objects.filter(recommend=True)
    num = 7 if len(blogs) >= 7 else len(blogs) 
    author_blogs = random.sample(list(blogs), num)
    return sorted(author_blogs, key=lambda x: x.publish_time, reverse=True)

def blog_list_show(request, pages, blogs):
    random_blogs = random_recommend()    
    recommend_blogs = author_recommend()

    context = { 
        'blogs': blogs, 
        'pages': pages,  
        'random_blogs': random_blogs, 
        'recommend_blogs': recommend_blogs,
    }
    return render(request, 'blog/blog_list.html', context)

def blog_index(request):
    """ 显示博客的列表 """
    blogs = Blog.objects.all()
    pages, blogs = getPages(request, blogs)
    return blog_list_show(request, pages, blogs)

@record_view(Blog)
def blog_show(request, blog_id):
    """ 显示单篇博客的内容 """
    cur_blog = Blog.objects.get(id=blog_id)

    # 检查该篇博文的阅读记录是否存在于cookies中，若无则阅读量+1
    if str("blog_%s_readed" % (blog_id)) not in request.COOKIES:
        cur_blog.read_num += 1
        cur_blog.save()

    pre_blog = Blog.objects.filter(id__gt=blog_id).order_by('id')
    next_blog = Blog.objects.filter(id__lt=blog_id).order_by('-id')

    pre_blog = pre_blog[0] if pre_blog.count() > 0 else None
    next_blog = next_blog[0] if next_blog.count() > 0 else None

    random_blogs = random_recommend()
    recommend_blogs = author_recommend()

    comments = Comment.objects.filter(blog__id=cur_blog.id).order_by('publish_time')

    context = {
        'cur_blog': cur_blog,
        'pre_blog': pre_blog,
        'next_blog': next_blog,
        'comments': comments,
        'random_blogs': random_blogs,
        'recommend_blogs': recommend_blogs,
    }

    response = render(request, 'blog/blog_single.html', context)
    
    # 这里设置在浏览器被关闭之前不会重新对博文阅读数量进行计数
    response.set_cookie("blog_%s_readed" % (blog_id),"True")
    return response

def search_blog(request):
    try:
        wd = request.GET['wd']
        if not wd:
            return HttpResponseRedirect(reverse('blog:blog_index'))
    
        blogs = Blog.objects.filter(caption__icontains=wd)
        pages, blogs = getPages(request, blogs)
        return blog_list_show(request, pages, blogs)
    except Exception:
        raise Http404

def tag_blogs(request, tag_name):
    try:
        tag = Tag.objects.get(tag_name=tag_name)
        blogs = tag.blog_set.all()
        pages, blogs = getPages(request, blogs)
        return blog_list_show(request, pages, blogs)
    except Exception:
        raise Http404

def recommend_blogs(request):
    blogs = Blog.objects.filter(recommend=True)
    pages, blogs = getPages(request, blogs)
    return blog_list_show(request, pages, blogs)

# 评论相关视图函数

def new_comment(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    text = request.POST['comment_text']
    Comment.objects.create(blog=blog, author=request.user, content=text)
    text = str(request.user) + " have a new comment in your blog " + str(blog.caption) +\
            "[chick here](http://www.schnee.pro/blog/blog/" + str(blog.id) + ")"
    Message.objects.create(text=text, receiver=blog.author, sender=request.user)
    return HttpResponseRedirect(reverse('blog:blog_show', args=[blog_id]))

def delete_comment(request, blog_id, comment_id):
    try:
        del_comment = Comment.objects.get(id=comment_id)
        del_comment.delete()
    finally:
        return HttpResponseRedirect(reverse('blog:blog_show', args=[blog_id]))

blog/templates/blog/blog_list.html
{% extends "home/base.html" %} {% block title %} Blog {% endblock %} {% block content %} {% load static %} {% load base %}

<body>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <!-- Start about Area -->
    <section class="section-gap info-area" id="about">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="menu-content pb-40 col-lg-8">
                    <div class="title text-center">
                        <h1 class="mb-10">My blog</h1>
                    </div>
                </div>
            </div>
            <div>
                <div class="col-md-9" style="float:left">
                    <div class="blog-border">
                        {% for blog in blogs %}
                        <div class="blog-item">
                            <div class="blog-title">
                                <a href="{% url 'blog:blog_show' blog.id %}" style="color: #4682b4">{{ blog.caption }}</a>
                            </div>
                            <div class="blog-descipt">
                                {{ blog.content|striptags|safe|truncatechars:100 }}
                            </div>
                            <div class="blog-tags">
                                <ul>
                                    <li>{{ blog.publish_time|date:'M.d.Y' }}</li>
                                    <li>阅读: {{ blog.read_num }}</li>
                                    <li>评论：{{ blog.id|get_comment_count }}</li>
                                    <li>
                                        {% for tag in blog.id|get_all_blog_tags %}
                                        <span class="glyphicon glyphicon-tag"> </span>
                                        <a href="{% url 'blog:tag_blogs' tag %}">{{ tag }}  </a> {% endfor %}
                                    </li>
                                    {% ifequal blog.recommend True %}
                                    <li>
                                        <div style="color:B22222">
                                            <span class="glyphicon glyphicon-thumbs-up" style="color:#B22222"></span>
                                            <a href="{% url 'blog:recommend_blogs' %}" style="color:#B22222">推荐</a>
                                        </div>
                                    </li>
                                    {% endifequal %}
                                </ul>
                            </div>
                        </div>
                        {% empty %}
                        <div class="blog-item">
                            <div class="blog-title">
                                <p>search no result QAQ</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-3" style="float:left; padding:0px; margin-bottom: 10px">
                    <form action="{% url 'blog:search_blog'%}">
                        <input name="wd" type="text" placeholder="  查找博客" class="form-control-button" style="width: 230px">
                        <button type="submit"> <span class="glyphicon glyphicon-search"></span>
                    </button>
                    </form>
                </div>
                <div class="col-md-3" style="float:left; padding:0px">
                    <div class="blog-border">
                        <div class="blog-title" style="padding: 10px; margin: 0px">
                            <span class="lnr lnr-book"></span> 作者推荐
                            <hr/ style="margin: 5px">
                        </div>
                        {% for blog in recommend_blogs %}
                        <div style="padding-left: 10px">
                            <a href="{% url 'blog:blog_show' blog.id %}" style="color: #4682b4">{{ blog.caption|truncatechars:20 }}</a>
                        </div>
                        {% endfor %}
                        <br/>
                        <div class="blog-title" style="padding: 10px; margin: 0px">
                            <span class="lnr lnr-book"></span> 随机推荐
                            <hr/ style="margin: 5px">
                        </div>
                        {% for blog in random_blogs %}
                        <div style="padding-left: 10px">
                            <a href="{% url 'blog:blog_show' blog.id %}" style="color: #4682b4">{{ blog.caption|truncatechars:20 }}</a>
                        </div>
                        {% endfor %}
                        <br/>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <br/>
        <div class="container">
            <div class="text-center" style="float:none">
                <div>
                    共{{pages.count}}篇博文。当前第{{blogs.number}}页，共{{pages.num_pages}}页
                </div>
                <div class="blog-pages" style="display: inline-table">
                    <ul>
                        <li class="page_li">
                            {% if blogs.has_previous %}
                            <a href="?page={{blogs.previous_page_number}}" aria-label="Previous" class="btn btn-default" style="border: #6e9fc7 1px solid;  margin: 10px;">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            {% else %}
                            <a href="?page={{blogs.number}}" aria-label="Previous" class="btn btn-default" style="border: #6e9fc7 1px solid;  margin: 10px;">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                            {% endif %}

                        </li>

                        {% for page in pages.page_range %}
                        <li class="page_li"><a href="?page={{page}}" class="btn btn-default" style="border: #6e9fc7 1px solid;  margin: 10px;">{{page}}</a></li>
                        {% endfor %}
                        <li class="page_li">
                            {% if blogs.has_next %}
                            <a href="?page={{blogs.next_page_number}}" aria-label="Next" class="btn btn-default" style="border: #6e9fc7 1px solid;  margin: 10px;">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            {% else %}
                            <a href="?page={{blogs.number}}" aria-label="Next" class="btn btn-default" style="border: #6e9fc7 1px solid;  margin: 10px;">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            {% endif %}

                        </li>
                    </ul>
                </div>

                {% block extra_footer %} {#设置凸显当前的页码#}
                <script type="text/javascript">
                    $(".pagination li:eq({{blogs.number}})").addClass("active");
                </script>
                {% endblock %}
            </div>

    </section>
</body>
{% endblock content %}

blog/templates/blog/blog_single.html
{% extends "home/base.html" %} {% block title %} New Blog {% endblock %} {% block content %} {% load static %} {% load bootstrap4 %} {% load base %}


<link rel="stylesheet" href="{% static 'css/blog.css' %}">
<link href="https://cdn.bootcss.com/highlight.js/9.13.1/styles/github-gist.min.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
</script>

<script>
    function delBlogConfirm() {
        event.returnValue = confirm("Are you sure to delete this blog?")
    }
</script>

<body onload="prettyPrint()">
    <!-- Start about Area -->
    <section class="section-gap info-area">
        <div class="container">
            <div>
                <div class="col-md-9" style="float:left">
                    <div class="blog-border">
                        <div class="panel-heading">
                            <div class="blog_header">
                                <h3>{{ cur_blog.caption }}</h3>
                                <br/>
                                <div>
                                    <ul>
                                        <li>{{ cur_blog.publish_time|date:'M.d.Y' }}</li>
                                        <li>阅读: {{ cur_blog.read_num }}</li>
                                        <li>评论：{{ cur_blog.id|get_comment_count }}</li>
                                        <li>
                                            {% for tag in cur_blog.id|get_all_blog_tags %}
                                            <span class="glyphicon glyphicon-tag"> </span>
                                            <a href="{% url 'blog:tag_blogs' tag %}">{{ tag }}  </a> {% endfor %}
                                        </li>
                                        {% ifequal blog.recommend True %}
                                        <li>
                                            <span class="glyphicon glyphicon-thumbs-up" style="color:#B22222"></span>
                                            <a href="{% url 'blog:recommend_blogs' %}" style="color:#B22222">推荐</a>
                                        </li>
                                        {% endifequal %}
                                    </ul>
                                </div>

                            </div>
                        </div>
                        <hr/>
                        <div class="panel-body">
                            <div class="blog_content">
                                {{ cur_blog.content|safe }}
                                <!-- {{ cur_blog.content|safe }} -->
                                <!-- {{ cur_blog.content | custom_markdown }} -->
                            </div>
                        </div>
                        <br/>
                    </div>
                </div>
                <div class="col-md-3" style="float:left; padding:0px">
                    <div class="blog-border">
                        <div class="blog-title" style="padding: 10px; margin: 0px">
                            <span class="lnr lnr-book"></span> 作者推荐
                            <hr/ style="margin: 5px">
                        </div>
                        {% for blog in recommend_blogs %}
                        <div style="padding-left: 10px">
                            <a href="{% url 'blog:blog_show' blog.id %}" style="color: #4682b4">{{ blog.caption|truncatechars:20 }}</a>
                        </div>
                        {% endfor %}
                        <br/>
                        <div class="blog-title" style="padding: 10px; margin: 0px">
                            <span class="lnr lnr-book"></span> 随机推荐
                            <hr/ style="margin: 5px">
                        </div>
                        {% for blog in random_blogs %}
                        <div style="padding-left: 10px">
                            <a href="{% url 'blog:blog_show' blog.id %}" style="color: #4682b4">{{ blog.caption|truncatechars:20 }}</a>
                        </div>
                        {% endfor %}
                        <br/>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        </div>
    </section>
    <!-- End about Area -->
    <div class="col-md-9">
        <p>
            {% if pre_blog %}
            <a href="{% url 'blog:blog_show' pre_blog.id %}">上一篇：{{pre_blog.caption}}</a> {% else %} 上一篇：没有了 {% endif %}
        </p>
        <p>
            {% if next_blog %}
            <a href="{% url 'blog:blog_show' next_blog.id %}">下一篇：{{next_blog.caption}}</a> {% else %} 下一篇：没有了 {% endif %}
        </p>
        <br/>
    </div>

    <div class="container">
        <div class="col-md-9" style="float: left">
            <div class="blog-border" style="padding: 12px">
                <!-- <h5>Comments:</h5> -->
                <h5>评论列表</h5>
                <hr/> {% for comment in comments %}
                <h5>{{ comment.author }}</h5>
                <div style="float:right">
                    <a href="{% url 'users:add_as_friend' comment.author.id %}"><span class="glyphicon glyphicon-plus"></span></a> {% if request.user == cur_blog.author %}
                    <a href="{% url 'blog:delete_comment' cur_blog.id comment.id %}"><span class="glyphicon glyphicon-trash"></span></a> {% elif request.user == comment.author %}
                    <a href="{% url 'blog:delete_comment' cur_blog.id comment.id %}"><span class="glyphicon glyphicon-trash"></span></a> {% endif %}
                    <div class="clear"></div>
                </div>
                <br/>
                <div class="col-md-11">
                    {{ comment.content }}
                </div>
                <div style="float:right">
                    <p>{{ comment.publish_time }}</p>
                    <div class="clear"></div>
                </div>
                <br/>
                <hr/> {% endfor %}
            </div>
        </div>
        <div class="clear"></div>
    </div>
    <br/> {% if user.is_authenticated %}
    <div class="container">
        <div class="col-md-9" style="float: left">
            <div class="blog-border" style="padding: 12px">
                <!-- <h5>New comment</h5> -->
                <h5>添加新的评论</h5>
                <br/>
                <form action="{% url 'blog:new_comment' cur_blog.id %}" method='post' class="form">
                    {% csrf_token %}
                    <textarea type="text" name='comment_text' id='comment_text' class='form-control' rows="4"></textarea>
                    <br/>
                    <div align="right">
                        {% buttons %}<button name="submit" class="btn btn-primary">添加评论<!--Add comment--></button> {% endbuttons %}
                    </div>
                </form>{{ form.media }}
            </div>
        </div>
        <div class="clear"></div>
    </div>
    {% else %}
    <div class="container">
        <div class="col-md-9" style="float: left">
            <div class="blog-border" style="padding: 12px">
                <!-- <h5>Comment after login.</h5> -->
                <h5>登陆后评论</h5>
            </div>
        </div>
        <div class="clear"></div>
        <hr/>
    </div>
    {% endif %}
</body>
{% endblock content %}