home/urls.py
from django.urls import path
import django.views

from home import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home/', views.home, name = 'home'),
    path('gallery/', views.gallery, name = 'gallery'),
    path('lab/', views.lab, name = 'lab'),
    path('about/', views.about, name = 'about'),
    path('test_page/', views.test_page, name = 'test_page'),
    path('developing/', views.developing, name = 'developing'),
]

lab/urls.py
from django.urls import path
import django.views

from lab import views

app_name = 'lab'

urlpatterns = [
    # path('lab_index/', views.lab_index, name = 'lab_index'),
    path('text_embed/', views.text_embed, name = 'text_embed'),

    path('hash_verify/', views.hash_verify, name = 'hash_verify'),

    path('download_hash_verify/', views.download_hash_verify, name = 'download_hash_verify'),

    path('character_image/', views.character_image, name = 'character_image'),
]

schnee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace = 'home')), 
    path('blog/', include('blog.urls', namespace = 'blog')),
    path('lab/', include('lab.urls', namespace = 'lab')),
    path('users/', include('users.urls', namespace = 'users')),
    path('lenotes/', include('lenotes.urls', namespace = 'lenotes')),
    path('sonata/', include('sonata.urls', namespace = 'sonata')),
    path('markdownx/', include('markdownx.urls')),
    path('simditor/', include('simditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\

users/urls.py
from django.urls import path

from users import views
app_name = 'users'

urlpatterns = [
    # 基础功能
    path('login/', views.login_view, name = 'login'),

    path('logout/', views.logout_view, name = 'logout'),

    path('register/', views.register, name = 'register'),

    path('notice/', views.notice, name = 'notice'),

    path('settings/', views.settings, name = 'settings'),

    path('reset_password/', views.reset_password, name = 'reset_password'),

	path('reset_done/', views.reset_done, name = 'reset_done'),

    # 消息处理相关
    path('send_message/', views.send_message, name = 'send_message'),

    path('set_as_read/<int:message_id>', views.set_as_read, name = 'set_as_read'),

    path('read_message/<int:message_id>', views.read_message, name = 'read_message'),

    path('receiver_del_message/<int:message_id>', views.receiver_del_message, name = 'receiver_del_message'),

    path('sender_del_message/<int:message_id>', views.sender_del_message, name = 'sender_del_message'),

    # 好友，群组处理相关
    path('add_as_friend/<int:user_id>', views.add_as_friend, name = 'add_as_friend'),

    path('deal_invi/<int:message_id>/<int:accept>', views.deal_invi, name = 'deal_invi'),

    path('delete_friend/<str:username>', views.delete_friend, name = 'delete_friend'),

    path('quit_group/<int:group_id>', views.quit_group, name = 'quit_group'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

# Create your models here.

class UserInfo(models.Model):
    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    LANGUAGE_CHOICES = (
        (u'E', u'English'),
        (u'C', u'简体中文'),
    )
    user = models.OneToOneField(User, on_delete = models.CASCADE, related_name="user")
    nickname = models.CharField(max_length=20, default="Undefined")
    gender = models.CharField(max_length=6, choices=GENDER_CHOICES, default="Male")
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES, default="English")
    intro = models.CharField(max_length=200, default="hello world")
    email = models.EmailField(max_length=70, blank=True, default="Undefined@example.com")
    friends = models.ManyToManyField(User, blank=True, related_name="user_friends")
    profile = ProcessedImageField(upload_to='user/img', default='user/img/default.jpg', 
        processors=[ResizeToFill(500, 500)],  format='JPEG', options={'quality': 60})
    unread_count = models.IntegerField(default=0)
    
    def __str__(self):
        return self.nickname

class Message(models.Model):
    TYPE_CHOICES = (
        (u'M', u'Message'),
        (u'F', u'Friend_Invitation'),
        (u'G', u'Group_Invitation'),
    )
    sender = models.ForeignKey(User, related_name="sender_msg", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receiver_msg", on_delete=models.CASCADE)
    text = MarkdownxField(max_length=2000)
    id_content = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)
    msg_type = models.CharField(max_length=20, choices=TYPE_CHOICES, default="Message")
    is_deal = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    sender_del = models.BooleanField(default=False)
    receiver_del = models.BooleanField(default=False)
    
    def __str__(self):
        return self.text

users/forms.py
from django import forms
#from markdown import MarkdownFormField
from users.models import UserInfo, Message


#class ProfileForm(forms.Form):
 #   upProfile = forms.FileField()

class InfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = [
            'nickname',
            'gender',
            'language',
            'email',
            'intro',
        
        ]
        labels = {
            'nickname': 'Nickname',
            'gender': 'Gender',
            'language': 'Language',
            'email': 'Email',
            'intro': 'User introduce',
        }

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = [
            'text'
        ]
        labels = {
            'text': 'Content'
        }

users/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render

from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from users.models import UserInfo, Message
from users.forms import InfoForm, MessageForm

from lenotes.models import Group, Diary 

from helper.update_data import update_userInfo_unread_count

import re

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('home:home'))
    if request.method != 'POST':
        request.session['login_from'] = request.META.get('HTTP_REFERER', '/') 
        form = AuthenticationForm(request)
    else:
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return HttpResponseRedirect(request.session['login_from'])
    context = {'form': form}
    return render(request, 'users/login.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:home'))


def register(request):
    if request.method != 'POST':
        user_form = UserCreationForm()
        info_form = InfoForm()
    else:
        user_form = UserCreationForm(data=request.POST)
        info_form = InfoForm(request.POST, request.FILES)
        if user_form.is_valid():
            new_user = user_form.save()
            new_info = info_form.save(commit=False)
            new_info.user = new_user
            new_info.save()
            authenticated_user = authenticate(username = new_user.username,
            password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('home:home'))
    
    context = {
        'user_form': user_form,
        'info_form': info_form,    
    }
    return render(request, 'users/register.html' , context)


@login_required
def settings(request):
    if request.method != 'POST':
        try:
            info = UserInfo.objects.get(user = request.user)
        except ObjectDoesNotExist:
            info = UserInfo.objects.create(user = request.user)
        info_form = InfoForm(instance = info)
        context = {
            'info_form': info_form,
            'info': info,
        }
        return render(request, 'users/settings.html' , context)
    else:
        info_form = InfoForm(request.POST)
        if info_form.is_valid():
            try:
                info = UserInfo.objects.get(user = request.user)
            except ObjectDoesNotExist:
                info = UserInfo.objects.create(user = request.user)
        info.name = info_form.cleaned_data["nickname"]
        info.gender = info_form.cleaned_data["gender"]
        info.language = info_form.cleaned_data["language"]
        info.email = info_form.cleaned_data["email"]
        info.intro = info_form.cleaned_data["intro"]
        myprofile = request.FILES.get('profile',None)
        if myprofile:
            if info.profile.name != 'user/img/default.jpg' :
                info.profile.delete()
            info.profile = myprofile
        info.save()
        return HttpResponseRedirect(reverse('home:home'))


@login_required
def reset_password(request):
    if request.method != 'POST':
        form = PasswordChangeForm(user = request.user)
    else:
        form = PasswordChangeForm(user = request.user, data = request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('users:reset_done'))
    context = { 'form': form }
    return render(request, 'users/reset_password.html', context)


def reset_done(request):
    return render(request, 'users/reset_done.html')


@login_required
def notice(request):
    """ 用于接收信息以及查看发送的消息 """
    update_userInfo_unread_count(request.user)
    inbox_messages = Message.objects.filter(receiver=request.user).filter(receiver_del=False).order_by('-date_added')
    outbox_messages = Message.objects.filter(sender=request.user).filter(sender_del=False).order_by('-date_added')
    context = {
        'inbox_messages': inbox_messages,
        'outbox_messages': outbox_messages
    }
    return render(request, 'users/mailbox.html', context)


@login_required
def send_message(request):
    """ 向某人发送信息 / 支持群发 """
    if request.method != 'POST':
        form = MessageForm()
    else:
        form = MessageForm(request.POST, request.FILES)
        if form.is_valid():
            tmp_message = form.save(commit=False)
            username_list = request.POST['receiver_id']
            username_list = re.split(r'[\s\,\;]+', username_list)
            for username in username_list:                
                if username.strip() == "":
                    continue
                try:
                    receiver_user = User.objects.get(username=username.strip())
                except ObjectDoesNotExist:
                    return render(request, 'users/userIsNotExist.html')
                Message.objects.create(text=tmp_message.text, receiver=receiver_user, sender=request.user)
            return HttpResponseRedirect(reverse('home:home'))
    
    info_id = UserInfo.objects.get(user=request.user).id
    context = {'form': form, 'info_id': info_id}
    return render(request, 'users/send_message.html', context)


@login_required
def set_as_read(request, message_id):
    """ 标记消息为已读 """
    try:
        message = Message.objects.get(id=message_id)
        if request.user == message.receiver:
            message.is_read = True
            message.save()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))


@login_required
def read_message(request, message_id):
    """ 阅读消息完整内容并回复 """
    message = Message.objects.get(id=message_id)
    if request.user == message.receiver:
        message.is_read = True
        message.save()

    if request.method != 'POST':
        form = MessageForm()
    else:
        form = MessageForm(request.POST, request.FILES)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.receiver = message.sender
            new_message.sender = request.user
            new_message.save()
            return HttpResponseRedirect(reverse('users:notice'))
    
    context = {'message': message, 'form': form}
    return render(request, 'users/read_message.html', context)


@login_required
def receiver_del_message(request, message_id):
    """ 收信者删除当前消息，若发送者已删除，则删除该信息 """
    try:
        del_message = Message.objects.get(id=message_id)
        del_message.receiver_del = True
        if del_message.sender_del == True:
            del_message.delete()
        else:
            del_message.save()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))


@login_required
def sender_del_message(request, message_id):
    """ 发送者删除当前消息，若收信者已删除，则删除该信息 """
    try:
        del_message = Message.objects.get(id=message_id)
        del_message.sender_del = True
        if del_message.receiver_del == True:
            del_message.delete()
        else:
            del_message.save()
    finally:
        return HttpResponseRedirect(reverse('users:notice'))


@login_required
def add_as_friend(request, user_id):
    """点击+向对方发送添加好友的请求"""
    receiver = User.objects.get(id = user_id)
    user = UserInfo.objects.get(user = request.user)
    context = {'isSuccess':False}

    if receiver not in user.friends.all():
        context['isSuccess'] = True
        text = str(request.user.username) + " wants to add you as a friend."
        Message.objects.create(sender=request.user, receiver=receiver, text=text, msg_type="Friend_Invitation")    
    
    return render(request, 'users/send_invi.html', context)


@login_required
def deal_invi(request, message_id, accept):
    """ 根据邀请类型分别处理好友邀请以及群组邀请 """
    message = Message.objects.get(id=message_id)
    message.is_deal = True
    message.save()

    # 处理好友邀请
    if message.msg_type == "Friend_Invitation":
        if accept:
            send_user_info = UserInfo.objects.get(user=message.sender)
            rece_user_info = UserInfo.objects.get(user=request.user)
            send_user_info.friends.add(request.user)
            rece_user_info.friends.add(message.sender)
            text = "I have added you as friend."
        else:
            text = "Sorry, I refuse to add you as friend."
        
        Message.objects.create(sender=request.user, receiver=message.sender, text=text)
        context = {"username": message.sender.username, "accept":accept}

        return render(request, 'users/deal_invi.html', context)

    
    # 处理群组邀请
    elif message.msg_type == "Group_Invitation":
        group = Group.objects.get(id=message.id_content)
        if accept:
            group.members.add(request.user)
            text = request.user.username + " accpeted to join in group:" + group.name
        else:
            text = request.user.username + " refused to join in group:" + group.name
        Message.objects.create(sender=request.user, receiver=group.owner, text=text)
        return HttpResponseRedirect(reverse('users:notice'))

    # 测试用的错误报告
    else:
        raise "Error msg type"


@login_required
def delete_friend(request, username):
    del_user = User.objects.get(username=username)
    user_info = UserInfo.objects.get(user=request.user)
    user_info.friends.remove(del_user)
    # user_info.save()
    del_user_info = UserInfo.objects.get(user=del_user)
    del_user_info.friends.remove(request.user)
    # del_user_info.save()
    text = "Sorry, you have be delete by " + str(request.user.username) + "."

users/templates/users/deal_invi.html
{% extends "home/base.html" %} {% load widget_tweaks %} {% block title %}Error in invite{% endblock title %} {% block content %}

<body>
    <div class="section-top-border">
    	{% if accept %}
        	<h1>You have accept {{ username }} as your friend.</h1>
        {% else %}
        	<h1>You refuse to accept {{ username }} as your friend.</h1>
        {% endif %}
        <br/>
        <a href="{% url 'users:notice' %}" class="btn btn-primary">comfirm</a>
    </div>
</body>
{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load widget_tweaks %} {% block title %}Log in{% endblock title %} {% block stylesheet %} {% endblock stylesheet %} {% block content %} {% load static %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<body>

    <div class="section">
        {% if user.is_authenticated %}
        <p>You have login. Go back to <a href="{% url 'home:home' %}">index</a></p>
        {% else %}

        <div class="mycontainer" style="margin-top: 240px">
            <center>
                <h2>Login</h2>
            </center>
            <br/>
            <form class="" method="post" action="{% url 'users:login' %}" novalidate>
                {% csrf_token %} {% if form.errors %}
                <p style="text-align: center; color: grey; font-size: 24px; ">Incorrect username or password.</p>
        </div class="col-xs-4">
        {% endif %}
        <label for="id_username" class="form-control sr-only">Username</label> {{ form.username | add_class:"form-control" | attr:"placeholder:Username"}}
        <p></p>
        <label for="id_password" class="form-control sr-only">Password</label> {{ form.password | add_class:"form-control" | attr:"placeholder:Password"}}
        <p></p>
        <center>
            <button class="btn btn-primary form-control-button" type="submit" name="submit">Log in</button>
        </center>
        <input type="hidden" name="next" value="{{ next }}" />
        </form>
    </div>
    {% endif %}
    </div>
</body>
{% endblock content %}

users/templates/users/mailbox.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %}{% block content %}

<body>
    <div class="section-top-border">
        <h1>Mailbox</h1>
        <br/>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Inbox Message</th>
                    <th>Sender</th>
                    <th>Content</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for message in inbox_messages %} {% ifequal message.is_read False %}
                <tr class="table-info">
                    <td>{{ message.date_added|date:'M d, Y H:i' }}</td>
                    <td>{{ message.sender }}</td>
                    {% if message.text|length > 40 %}
                    <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                    {% else %}
                    <td>{{ message.text}}</td>
                    {% endif %}
                    <td>

                        {% ifequal message.msg_type "Message" %}
                        <a href="{% url 'users:set_as_read' message.id %}" title="comfirm">
                            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                        </a>
                        {% else %}
                        <a href="{% url 'users:read_message' message.id %}" title="Read and reply">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>
                        {% endifequal %}
                    </td>
                    <td></td>
                </tr>
                {% else %}
                <tr>
                    <td>{{ message.date_added|date:'M d, Y H:i' }}</td>
                    <td>{{ message.sender }}</td>
                    {% if message.text|length > 40 %}
                    <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                    {% else %}
                    <td>{{ message.text}}</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'users:read_message' message.id %}" title="Read and reply">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'users:receiver_del_message' message.id %}" title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>

                    </td>
                </tr>
                {% endifequal %} {% empty %}
                <tr>
                    <td>No message.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br/>
        <br/>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Outbox Message</th>
                    <th>Receiver</th>
                    <th>Content</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for message in outbox_messages %}
                <tr>
                    <td>{{ message.date_added|date:'M d, Y H:i' }}</td>
                    <td>{{ message.receiver.username }}</td>
                    {% if message.text|length > 40 %}
                    <td>{{ message.text|slice:'0 : 40' }} . . .</td>
                    {% else %}
                    <td>{{ message.text}}</td>
                    {% endif %}
                    <td>
                        <a href="{% url 'users:read_message' message.id %}" title="Read more">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'users:sender_del_message' message.id %}" title="Delete">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>

                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td>No message.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <br/>
        <h4>
            <a href="{% url 'users:send_message' %}" class="btn btn-default">Send Message</a>
            <a href="{% url 'home:home' %}" class="btn btn-default">Go Back</a></h4>
    </div>
</body>
{% endblock content %}

users/templates/users/read_message.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load bootstrap4 %}{% block content %} {% load base %}

<body>
    {% if message.msg_type == "Message" %}
    <div class="section-top-border">
        <h1>Read and reply</h1>
        <br/>
        <h4>Sender : {{ message.sender }}</h4>
        <br/>
        <p>{{ message.date_added }}</p>
        <h5>Content:</h5>
        <div style="border: 1px #ccc solid; border-radius: 6px; padding: 20px">{{ message.text | custom_markdown }}</div>
        <hr/>
        <h4>Reply to sender - {{ message.sender }}:</h4>
        <br/>
        <form action="{% url 'users:read_message' message.id %}" method="POST" class="form">{% csrf_token %}
            <div class="form-group">
                {% bootstrap_form form %}
            </div>
            <button type="submit" class="btn btn-primary">Send</button>
            <a href="{% url 'users:notice' %}" class="btn btn-default">Go Back</a>
        </form>{{ form.media }}
    </div>
    {% else %}
    <div class="section-top-border">
        <h1>Invitation</h1>
        <br/>
        <h4>Sender : {{ message.sender }}</h4>
        <br/>
        <p>{{ message.date_added }}</p>
        <h5>Content:</h5>
        <div style="border: 1px #ccc solid; border-radius: 6px; padding: 20px">{{ message.text | custom_markdown }}</div>
        {% ifequal message.is_deal False %}
        <a href="{% url 'users:deal_invi' message.id 1 %}" class="btn btn-success">Accept</a>
        <a href="{% url 'users:deal_invi' message.id 0 %}" class="btn btn-danger">Refuse</a> {% else %}
        <p>You have already processed this invitation.</p>
        {% endifequal %}
        <hr/>
    </div>

    {% endif %}
</body>
{% endblock content %}

users/templates/users/register.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load widget_tweaks %} {% block content %} {% load static %}

<link rel="stylesheet" href="{% static 'css/register.css' %}">

<body>
    <div class="section-top-border">
        <form class="form-users" method="post" enctype="multipart/form-data" action="{% url 'users:register' %}">
            {% csrf_token %}
            <center>
                <h2>Register</h2>
            </center>
            <hr>
            <div class="form-group form-register">
                {% for field in user_form %}
                <div class="form-group">
                    <span> {{ field.label }} </span> {{ field | add_class:"form-control"}}
                </div>
                {% endfor %} {{ user_form.media }} {% for field in info_form %}
                <div class="form-group">
                    <span>{{ field.label }}</span> {{ field | add_class:"form-control"}}
                </div>
                {% endfor %} {{ info_form.media }}

                <div class="form-group">
                    <span>Profile Photo(Only support english filename)</span>
                    <input type="file" name="profile" class="form-control" />
                </div>

            </div>
            <div style="text-align: center">
                <button name="submit" class="btn btn-primary">Register</button>
                <a class="btn btn-outline-primary" href="/">Go Back</a>
            </div>
            <input type="hidden" name="next" value="{% url 'home:home' %}" />
        </form>
        <div style="text-align: center">
            <p>Have an account? <a href="{% url 'users:login' %}">Click</a> to log in.</p>
        </div>
    </div>
</body>
{% endblock content %}

users/templates/users/reset_done.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load staticfiles %} {% load widget_tweaks %} {% block title %}Change Password{% endblock title %} {% block content %}

<body>
    <div class="section-top-border">
        <h2>Password change successful</h2>
        <p>Your password was changed.</p>
        <p><a href="{% url 'home:home' %}">Home</a></p>
    </div>
</body>
{% endblock content %}

users/templates/users/reset_password.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load widget_tweaks %} {% block content %}

<body>
    <div class="section-top-border">
        <center>
            <h2>Reset Password</h2>
        </center>
        <hr/>
        <div class="col-md-6" style="margin:0 auto">
            <form class="form-users myforms" method="post" action="{% url 'users:reset_password' %}" novalidate>
                {% csrf_token %} {% for field in form %}
                <div class="form-group">
                    <span>{{ field.label }}</span> {{ field | add_class:"form-control"}}
                    <p class="error-message text-danger">
                        {% for error in field.errors %} {{ error }} {% endfor %}
                    </p>
                </div>
                {% endfor %}
                <center>
                    <button name="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" href="javascript:history.go(-1)">Go Back</a>
                </center>
            </form>
        </div>

    </div>
</body>
{% endblock content %}

users/templates/users/send_invi.html
{% extends "home/base.html" %} {% load widget_tweaks %} {% block title %}Error in invite{% endblock title %} {% block content %}

<body>
    <div class="section-top-border">
    	{% if isSuccess %}
        	<h1>Successfully send invitation.</h1>
        {% else %}
        	<h1>You are already friend!</h1>
        {% endif %}
        <br/>
        <a href="javascript:history.go(-1);" class="btn btn-primary">comfirm</a>
    </div>
</body>
{% endblock content %}

users/templates/users/settings.html
<!DOCTYPE html> {% extends "home/base.html" %} {% load widget_tweaks %} {% block content %} {% load base %} {% load static %}

<link rel="stylesheet" href="{% static 'css/settings.css' %}">

<script>
    function delFriendConfirm() {
        event.returnValue = confirm("Are you sure to delete this friend?")
    }
</script>

<body>
    <div class="section-top-border">
        <h2>Settings</h2>
        <div class="col-md-9" style="float:left">
            <form action="{% url 'users:settings' %}" enctype="multipart/form-data" method='post' novalidate class="myforms">
                {% csrf_token %}
                <hr/> {% for field in info_form %}
                <div class="form-group">
                    <span>
                    {{ field.label }}
                </span> {{ field | add_class:"form-control"}}
                    <p class="error-message text-danger">
                        {% for error in field.errors %} {{ error }} {% endfor %}
                    </p>
                </div>
                {% endfor %} {{ info_form.media }}

                <div class="form-group">
                    <span>Profile Photo(Only support english filename)</span>
                    <input type="file" name="profile" class="form-control" />
                </div>

                <div style="text-align: center">
                    <button name="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" href="/">Go Back</a>
                </div>
            </form>
        </div>
        <div class="col-md-3" style="float:left; padding:0px">
            <div class="settings-border">
                <div class="settings-title" style="padding: 10px; margin: 0px">
                    <span class="lnr lnr-book"></span> Friends
                    <hr/ style="margin: 5px">
                </div>
                {% for friend in info.id|get_friends %}
                <div style="padding-left: 30px">{{ friend }}
                    <div style="float:right; padding-right:30px">
                        <a href="{% url 'users:delete_friend' friend %}" onclick="delFriendConfirm()" title="delete friend">
                            <span class="glyphicon glyphicon-minus"></span></a>
                    </div>
                </div>
                {% endfor %} <br/>
            </div>
        </div>
        <div class="col-md-3" style="float:left; padding:0px; margin-top: 50px">
            <div class="settings-border">
                <div class="settings-title" style="padding: 10px; margin: 0px">
                    <span class="lnr lnr-cog"></span> Functions
                    <hr/ style="margin: 5px">
                </div>
                <div style="padding: 10px; margin: 0px">
                    <a class="btn btn-primary" href="{% url 'users:send_message' %}">Send Message</a>
                </div>
                <div style="padding: 10px; margin: 0px">
                    <a class="btn btn-primary" href="{% url 'users:reset_password' %}">Reset Password</a>
                </div>

            </div>
        </div>
        <div class="clear"></div>
    </div>

</body>
{% endblock content %}